#!/system/bin/sh
#代码来自https://u.qqcn.xyz/QkccEM

local downloadUrl="$1"
local md5="$2"
downloader_result=""
local hisotry="$START_DIR/downloader/path/$md5"
if [[ -f "$hisotry" ]]; then
    local abs_path=`cat "$hisotry"`
    if [[ -f "$abs_path" ]]; then
        local local_file=`md5sum "$abs_path"`
        if [[ "$local_file" = "$md5" ]]; then
            downloader_result="$abs_path"
            return
        fi
    fi
fi
local task_id=`cat /proc/sys/kernel/random/uuid`
activity="$Package_name/.ActionPageOnline"
am start -a android.intent.action.MAIN -n "$activity" --es downloadUrl "$downloadUrl" --ez autoClose true --es taskId "$task_id" 1 > /dev/null
if [[ "$md5" != "" ]]; then
    local hisotry="$START_DIR/downloader/path/$md5"
    if [[ -f "$hisotry" ]]; then
        downloader_result=`cat "$hisotry"`
    else
        echo '下载完成，但文件MD5与预期的不一致' 1>&2
    fi
else
    downloader_result=`cat $START_DIR/downloader/result/$task_id`
fi